### Add a new candidate
POST http://localhost:3000/candidates
Content-Type: application/json

{
  "name": "Johntur Doe",
  "phone": "1234987497890",
  "email": "johnd48@example.com",
  "gender": "Male",
  "experience": "2 Years",
  "skills": "JavaScript, Python"
}

### Retrieve all candidates
GET http://localhost:3000/candidatesGet
